export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_LINK = 'CREATE_LINK'
export const FETCH_LINKS = 'FETCH_LINKS'
export const ADD_NEW_TARGET = 'ADD_NEW_TARGET'
export const DELETE_TARGET = 'DELETE_LIST'
